// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmozptzjskyvzfghrtlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imptb3pwdHpqc2t5dnpmZ2hydGx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzk2NjgsImV4cCI6MjA3MDk1NTY2OH0.-mnClZqjIrXL-6mU16HgFKwbJdCgaLHcybmDz1sSW0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});